create index ai_runs_idea_owner_idx on public.ai_runs(idea_id, owner_id);
create index ai_runs_owner_idx on public.ai_runs(owner_id);
create index evaluations_idea_owner_idx on public.evaluations(idea_id, owner_id);
create index evaluations_owner_idx on public.evaluations(owner_id);
create index idea_embeddings_idea_owner_idx on public.idea_embeddings(idea_id, owner_id);
create index idea_embeddings_owner_idx on public.idea_embeddings(owner_id);
create index idea_relationships_owner_idx on public.idea_relationships(owner_id);
create index idea_relationships_source_owner_idx on public.idea_relationships(source_idea_id, owner_id);
create index idea_relationships_target_owner_idx on public.idea_relationships(target_idea_id, owner_id);
create index idea_versions_idea_owner_idx on public.idea_versions(idea_id, owner_id);
create index idea_versions_owner_idx on public.idea_versions(owner_id);
create index outcomes_idea_owner_idx on public.outcomes(idea_id, owner_id);
create index outcomes_project_owner_idx on public.outcomes(project_id, owner_id);
create index outcomes_owner_idx on public.outcomes(owner_id);
create index projects_idea_owner_idx on public.projects(idea_id, owner_id);
create index recommendations_idea_owner_idx on public.recommendations(idea_id, owner_id);
create index recommendations_owner_idx on public.recommendations(owner_id);
create index signals_idea_owner_idx on public.signals(idea_id, owner_id);
create index tasks_project_owner_idx on public.tasks(project_id, owner_id);
create index tasks_owner_idx on public.tasks(owner_id);
